### ISSUE TITLE
Can not run project

### ISSUE THREAD

**Issue by yarivShamash** [rodgtr1/firestore-react-crud-app#2]
Hello, after cloning the repo and installing the packages with `npm install` I tried to run the app just like you did in [your video](https://www.youtube.com/watch?v=LCvBPsuHe6g&t=927s)

When I tried to run `npm run start`, the development engine crashes and I got the following message:
Starting the development server...

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/yarivshamash/Projects/firestore-react-crud/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/yarivshamash/Projects/firestore-react-crud/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/yarivshamash/Projects/firestore-react-crud/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/Users/yarivshamash/Projects/firestore-react-crud/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:80:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (/Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/yarivshamash/Projects/firestore-react-crud/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/yarivshamash/Projects/firestore-react-crud/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/yarivshamash/Projects/firestore-react-crud/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/yarivshamash/Projects/firestore-react-crud/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/yarivshamash/Projects/firestore-react-crud/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.12.2
```

I tried running it on Node.js v16.20.2 but it's not suitable with the peer dependency `@types/node`.

Did you encounter similar problems?
Do you have any recommendation of how to solve this issue?

**Comment by mdplaya** [comment]
Option 1: Set the OpenSSL legacy provider (Quickest solution):
On Mac/Linux:
   export NODE_OPTIONS=--openssl-legacy-provider
   npm start

On Windows:
   set NODE_OPTIONS=--openssl-legacy-provider
   npm start

Option 2: Downgrade Node.js (More permanent solution)
